---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nativeai.dev
  resources:
  - zeusapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nativeai.dev
  resources:
  - zeusapps/finalizers
  verbs:
  - update
- apiGroups:
  - nativeai.dev
  resources:
  - zeusapps/status
  verbs:
  - get
  - patch
  - update
