# permissions for end users to view zeusapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: zeusapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: zeusapp
    app.kubernetes.io/part-of: zeusapp
    app.kubernetes.io/managed-by: kustomize
  name: zeusapp-viewer-role
rules:
- apiGroups:
  - serverless.nativeai.dev
  resources:
  - zeusapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serverless.nativeai.dev
  resources:
  - zeusapps/status
  verbs:
  - get
